/** 南伝大蔵経 増支部11集 — 集名・巻·主要経 */
export const NIPATAS = [
  {
    n: 1,
    shortTitle: '一の法',
    japanese: '一集',
    volume: '第17巻',
    mapNote: 'AN 1.1–1.77·精勤·念·慚愧·八正道——今日これ一つ、一法で育つ道',
    suttas: ['AN 1 一集（Ekkanipāta）'],
  },
  {
    n: 2,
    shortTitle: '二の法',
    japanese: '二集',
    volume: '第17巻',
    mapNote: 'AN 2.1–2.20·二法·二支·二縁——二つを守る、二つを見分ける',
    suttas: ['AN 2 二集（Dukanipāta）'],
  },
  {
    n: 3,
    shortTitle: '三の法',
    japanese: '三集',
    volume: '第17–18巻',
    mapNote: 'AN 3.27·61·65·78·88–90·95·101·109——三毒·三学·三受·三友·三尋·三業·三福行',
    suttas: ['AN 3 三集（Tikanipāta）'],
  },
  {
    n: 4,
    shortTitle: '四の法',
    japanese: '四集',
    volume: '第18巻',
    mapNote: 'AN 4.1–4.20·四諦·四念処·四無量心·四神足',
    suttas: ['AN 4 四集（Catukkanipāta）'],
  },
  {
    n: 5,
    shortTitle: '五の法',
    japanese: '五集',
    volume: '第18–19巻',
    mapNote: 'AN 5.1–5.30·五蓋·五取蘊·五力·五戒',
    suttas: ['AN 5 五集（Pañcakanipāta）'],
  },
  {
    n: 6,
    shortTitle: '六の法',
    japanese: '六集',
    volume: '第19巻',
    mapNote: 'AN 6.1–6.20·六念·六和敬·六入処·六念住',
    suttas: ['AN 6 六集（Chakkanipāta）'],
  },
  {
    n: 7,
    shortTitle: '七の法',
    japanese: '七集',
    volume: '第19–20巻',
    mapNote: 'AN 7.1–7.20·七覚支·七種聖財·七善士法',
    suttas: ['AN 7 七集（Sattakanipāta）'],
  },
  {
    n: 8,
    shortTitle: '八の法',
    japanese: '八集',
    volume: '第20巻',
    mapNote: 'AN 8.36·39·40·53·54·63·65·70·81——八正道·八念·八勝処·八解脱',
    suttas: ['AN 8 八集（Aṭṭhakanipāta）'],
  },
  {
    n: 9,
    shortTitle: '九の法',
    japanese: '九集',
    volume: '第21巻',
    mapNote: 'AN 9.1·3·5·12·20·37·41——九善·九不善·九怨·九処·九次第定',
    suttas: [
      'AN 9.1 九善法',
      'AN 9.2 九不善法',
      'AN 9.3 九怨因',
      'AN 9.5 九次第',
      'AN 9.12 九処',
      'AN 9.20 九想',
      'AN 9.37 九次第定',
      'AN 9.41 九支聖道',
    ],
  },
  {
    n: 10,
    shortTitle: '十の法',
    japanese: '十集',
    volume: '第21–22巻',
    mapNote: 'AN 10.1·27·60·95·103·176——十法·十見·十徳·十善業·慈経',
    suttas: [
      'AN 10.1 十法',
      'AN 10.27 十非見',
      'AN 10.60 十徳',
      'AN 10.95 純陀経',
      'AN 10.103 十善業',
      'AN 10.176 慈経',
    ],
  },
  {
    n: 11,
    shortTitle: '十一の法',
    japanese: '十一集',
    volume: '第22巻',
    mapNote: 'AN 11.1–11.16——十一法·一法の利益·漏尽への道',
    suttas: [
      'AN 11.1 一法の利益',
      'AN 11.2 二法の利益',
      'AN 11.3–11.10 三至十法',
      'AN 11.11–11.16 十一法',
    ],
  },
];

export function metaForNipata(n) {
  return NIPATAS.find((p) => p.n === n) || null;
}
